scout_base_login_check:
    path:     /login_check
    schemes:  [https]

scout_base_login:
    path:     /login
    defaults: { _controller: ScoutEventBaseBundle:Default:login }
    schemes:  [https]

scout_base_logout:
    path:     /logout

scout_base_app_list:
    path:     /
    defaults: { _controller: ScoutEventBaseBundle:Default:appList }
    schemes:  [https]

scout_base_user_list:
    path:     /users
    defaults:
        _controller: ScoutEventBaseBundle:Users:list
        roles: [ ROLE_ADMIN_USER ]
        application:
            icon: fa-smile-o
            name: User Admin

scout_base_user_create:
    path:     /users/create
    defaults:
        _controller: ScoutEventBaseBundle:Users:create
        roles: [ ROLE_ADMIN_USER ]

scout_base_user_edit:
    path:     /users/edit/{userId}
    defaults:
        _controller: ScoutEventBaseBundle:Users:edit
        roles: [ ROLE_ADMIN_USER ]
